default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: ruka
  password: 27729212

development:
  <<: *default
  database: meeteam_test

test:
  <<: *default
  database: meeteam_test